common: &common
  adapter: sqlite3
  username: root
  password: 
  host: localhost
  database: <%= APPNAME %>

test:
  <<: *common

development:
  <<: *common

production:
  encoding: unicode
  adapter: postgresql
  username: username
  port: 5432 
  host: hostname
    