common: &common
  adapter: sqlite3
  username: root
  password: 
  host: localhost
  database: acidimages.db

test:
  <<: *common

development:
  <<: *common

production:
  <<: *common
  host: hostname
    