common: &common
  adapter: sqlite3
  username: root
  password: 
  host: localhost
  database: <%= APPNAME %>

test:
  <<: *common

development:
  <<: *common

production:
  <<: *common
  adapter: postgres
